import type { GalleryConfig } from "@/types/galleryConfig";

// 相册配置
export const galleryConfig: GalleryConfig = {
	// 相册列表
	albums: [
		// 支持jpg/png/webp/avif/gif格式
		// id: 相册唯一标识符（用于目录命名和URL路径），比如设置：id: "firefly-2026", 对应 public/gallery/firefly-2026/目录
		// cover: 手动指定封面图（可选，不填会把cover.*文件作为封面图，如果没有cover.*文件，则使用第一张图片作为封面图）
		// name: 相册名称
		// description: 相册描述
		// location: 相册拍摄地点
		// date: 相册日期，格式为 YYYY-MM-DD，用于排序和显示
		// tags: 相册标签，用于分类和过滤
		// password: 访问密码，设置后需要输入密码才能查看相册内容（可选）
		// passwordHint: 密码提示，设置后在输入密码错误时显示（可选，需配合password使用）
		// 每添加一个数组项就相当于添加了一个相册，记得在 public/gallery/ 目录下创建对应的子目录并放入图片
		{
			id: "encrypted-test",
			name: "加密相册示例",
			description:"这是一个加密相册的示例，设置了访问密码，只有输入正确的密码才能查看相册内容。",
			location: "崩坏：星穹铁道",
			date: "2026-02-01",
			tags: ["加密相册"],
			password: "123456",
			passwordHint: "示例密码123456",
		},
        {
			id: "firefly",
			name: "流萤",
			description: "飞萤之火自无梦的长夜亮起，绽放在终竟的明天。 希望在旅途的终点....每个人都能抵达向往的结局。",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "流萤"],
		},
        {
			id: "hyacine",
			name: "风堇",
			description: "如果传说有虚假的成分...那它背后一定有必须被粉饰的理由。",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "风堇"],
		},
        {
			id: "robin",
			name: "知更鸟",
			description: "年少的时光稍纵即逝，但那些灿若繁星的回忆却是成长的礼物，值得被永远珍藏。",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "知更鸟"],
		},
        {
			id: "sunaookami-shiroko",
			name: "砂狼白子",
			description: "...",
			location: "蔚蓝档案",
			date: "2026-06-24",
			tags: ["蔚蓝档案", "砂狼白子"],
		},
        {
			id: "skirk",
			name: "丝柯克",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "丝柯克"],
		},
        {
			id: "herta",
			name: "黑塔",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "黑塔"],
		},
        {
			id: "stelle",
			name: "星",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "星"],
		},
        {
			id: "flying-snow",
			name: "爱弥斯",
			description: "...",
			location: "鸣潮",
			date: "2026-06-24",
			tags: ["鸣潮", "爱弥斯"],
		},
        {
			id: "cartethyia",
			name: "卡提希娅",
			description: "...",
			location: "鸣潮",
			date: "2026-06-24",
			tags: ["鸣潮", "卡提希娅"],
		},
        {
			id: "yanfei",
			name: "烟绯",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "烟绯"],
		},
        {
			id: "citlali",
			name: "茜特菈莉",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "茜特菈莉"],
		},
        {
			id: "toyokawa-shouko",
			name: "丰川祥子",
			description: "...",
			location: "mygo",
			date: "2026-06-24",
			tags: ["mygo", "丰川祥子"],
		},
        {
			id: "emilia",
			name: "爱蜜莉雅",
			description: "...",
			location: "re0",
			date: "2026-06-24",
			tags: ["re0", "爱蜜莉雅"],
		},
        {
			id: "castorice",
			name: "遐蝶",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "遐蝶"],
		},
        {
			id: "yeshunguang",
			name: "叶瞬光",
			description: "...",
			location: "绝区零",
			date: "2026-06-24",
			tags: ["绝区零", "叶瞬光"],
		},
        {
			id: "denia",
			name: "达妮娅",
			description: "...",
			location: "鸣潮",
			date: "2026-06-24",
			tags: ["鸣潮", "达妮娅"],
		},
        {
			id: "belle",
			name: "铃",
			description: "...",
			location: "绝区零",
			date: "2026-06-24",
			tags: ["绝区零", "铃"],
		},
        {
			id: "lumine",
			name: "荧",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "荧"],
		},
        {
			id: "ganyu",
			name: "甘雨",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "甘雨"],
		},
        {
			id: "shenhe",
			name: "申鹤",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "申鹤"],
		},
        {
			id: "hutao",
			name: "胡桃",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "胡桃"],
		},
        {
			id: "yoimiya",
			name: "宵宫",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "宵宫"],
		},
        {
			id: "drifter",
			name: "漂泊者",
			description: "...",
			location: "鸣潮",
			date: "2026-06-24",
			tags: ["鸣潮", "漂泊者"],
		},
        {
			id: "tsukatsuki-rio",
			name: "调月莉音",
			description: "...",
			location: "蔚蓝档案",
			date: "2026-06-24",
			tags: ["蔚蓝档案", "调月莉音"],
		},
        {
			id: "nachoneko",
			name: "甘城猫猫",
			description: "...",
			location: "Vtuber",
			date: "2026-06-24",
			tags: ["Vtuber", "甘城猫猫"],
		},
        {
			id: "ryuge-kisaki",
			name: "龙华妃咲",
			description: "...",
			location: "蔚蓝档案",
			date: "2026-06-24",
			tags: ["蔚蓝档案", "龙华妃咲"],
		},
        {
			id: "chisaki",
			name: "千咲",
			description: "...",
			location: "鸣潮",
			date: "2026-06-24",
			tags: ["鸣潮", "千咲"],
		},
        {
			id: "yunli",
			name: "云璃",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "云璃"],
		},
        {
			id: "yao-guang",
			name: "爻光",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "爻光"],
		},
        {
			id: "silver-wolf",
			name: "银狼 ",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "银狼"],
		},
        {
			id: "kamizato-ayaka",
			name: "神里绫华",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "神里绫华"],
		},
        {
			id: "furina",
			name: "芙宁娜",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "芙宁娜"],
		},
        {
			id: "sparkle",
			name: "花火 ",
			description: "...",
			location: "崩坏：星穹铁道",
			date: "2026-06-24",
			tags: ["崩坏：星穹铁道", "花火"],
		},
        {
			id: "sangonomiya-kokomi",
			name: "珊瑚宫心海",
			description: "...",
			location: "原神",
			date: "2026-06-24",
			tags: ["原神", "珊瑚宫心海"],
		},
	],

	// 瀑布流最小列宽(px)，浏览器根据容器宽度自动计算列数，默认 240
	// 值越小列数越多，值越大列数越少
	columnWidth: 240,
};
